"""GravityShift v5 - safe, idempotent Blueprint installer.

Rules (spec section 8):
  * never unconditionally delete_asset on a contract path
  * unknown / incompatible assets are preserved, a safe fallback is created instead
  * every created asset carries GS_* metadata tags
"""

import json
import os

import unreal

PACKAGE_VERSION = "5.0.0-rc1"
ROOT = "/Game/GravityShift"
FALLBACK_ROOT = "/Game/GravityShift/NativeStarter/ZFlipBallV5"
LEGACY_BACKUP_ROOT = "/Game/GravityShift/_LegacyBackup/ZFlipBallV5"

# v2 six-direction assets generated by the retired installer. Their native
# parents no longer exist, so they are archived instead of left broken.
LEGACY_V2_ASSETS = [
    "/Game/GravityShift/Core/BP_GravityManager",
    "/Game/GravityShift/Components/BPC_GravityBody",
    "/Game/GravityShift/Components/BPC_Breakable",
    "/Game/GravityShift/Components/BPC_Resettable",
    "/Game/GravityShift/Blocks/BP_BlockBase",
    "/Game/GravityShift/Blocks/BP_Block_Static",
    "/Game/GravityShift/Blocks/BP_Block_Gravity",
    "/Game/GravityShift/Blocks/BP_Block_Breaker",
    "/Game/GravityShift/Interactions/BP_SurfaceModifierPanel",
    "/Game/GravityShift/Tests/BP_GravityDemoRoom",
    "/Game/GravityShift/NativeStarter/Blocks/BP_GS_BlockBase",
]

# (name, folder, native parent class)
TARGETS = [
    ("BP_GSGravityManager", "Core", unreal.GSGravityManager),
    ("BP_GSWorldStateManager", "Core", unreal.GSWorldStateManager),
    ("BP_GSRollingBallPawn", "Core", unreal.GSRollingBallPawn),
    ("BP_GSGravityGameMode", "Core", unreal.GSGravityGameMode),
    ("BP_GSBlockBase", "Blocks", unreal.GSBlockBase),
    ("BP_GSSurfaceModifierVolume", "Interactions", unreal.GSSurfaceModifierVolume),
    ("BP_GSLandingResponseVolume", "Interactions", unreal.GSLandingResponseVolume),
    ("BP_GSGravitySwitch", "Interactions", unreal.GSGravitySwitch),
    ("BP_GSSurfaceControllerDevice", "Interactions", unreal.GSSurfaceControllerDevice),
    ("BP_GSCheckpoint", "World", unreal.GSCheckpoint),
    ("BP_GSKillVolume", "World", unreal.GSKillVolume),
    ("BP_GSCollectible", "World", unreal.GSCollectible),
    ("BP_GSFinishGoal", "World", unreal.GSFinishGoal),
    ("BP_GSIntegratedDemoRoom", "Tests", unreal.GSIntegratedDemoRoom),
]

report = {"package_version": PACKAGE_VERSION, "created": [], "reused": [],
          "preserved": [], "fallbacks": [], "archived_legacy": [], "fail": False}


def ensure_folder(path):
    if not unreal.EditorAssetLibrary.does_directory_exist(path):
        unreal.EditorAssetLibrary.make_directory(path)


def asset_path(folder, name):
    return "%s/%s/%s" % (ROOT, folder, name)


def parent_matches(blueprint, native_class):
    """UBlueprint exposes get_blueprint_parent_class(); generated_class() has no
    get_super_class() in the Python binding (AttributeError -> would silently
    fail every match). Compare against the native class' static UClass."""
    try:
        parent = blueprint.get_blueprint_parent_class()
        if parent is None:
            return False
        return parent == native_class.static_class()
    except Exception:
        return False


def class_name(cls):
    """unreal.GSGravityManager -> 'GSGravityManager'.

    The Python binding exposes generated reflection classes; ``get_name()`` is
    an unbound method on the type, so derive the name from the type itself.
    """
    return getattr(cls, "__name__", str(cls))


def tag_asset(asset, origin, parent_class, contract):
    unreal.EditorAssetLibrary.set_metadata_tag(asset, "GS_Origin", origin)
    unreal.EditorAssetLibrary.set_metadata_tag(asset, "GS_PackageVersion", PACKAGE_VERSION)
    unreal.EditorAssetLibrary.set_metadata_tag(asset, "GS_ContractAsset", "true" if contract else "false")
    unreal.EditorAssetLibrary.set_metadata_tag(asset, "GS_ParentClass", parent_class)


def create_blueprint(folder, name, native_class, contract=True):
    path = asset_path(folder, name)
    ensure_folder("%s/%s" % (ROOT, folder))

    if unreal.EditorAssetLibrary.does_asset_exist(path):
        existing = unreal.load_asset(path)
        if parent_matches(existing, native_class):
            tag_asset(existing, "Native", class_name(native_class), contract)
            report["reused"].append(path)
            return path
        # Incompatible or unknown asset: preserve it and build a safe fallback.
        ensure_folder(FALLBACK_ROOT)
        fallback_path = "%s/%s" % (FALLBACK_ROOT, name)
        report["preserved"].append(path)
        if unreal.EditorAssetLibrary.does_asset_exist(fallback_path):
            report["reused"].append(fallback_path)
            return fallback_path
        path = fallback_path
        contract = False

    factory = unreal.BlueprintFactory()
    factory.set_editor_property("parent_class", native_class)
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    blueprint = asset_tools.create_asset(name, os.path.dirname(path), None, factory)
    if blueprint is None:
        report["fail"] = True
        return None

    unreal.BlueprintEditorLibrary.compile_blueprint(blueprint)
    tag_asset(blueprint, "Native", class_name(native_class), contract)
    unreal.EditorAssetLibrary.save_asset(path)
    (report["created"] if contract else report["fallbacks"]).append(path)
    return path


def archive_legacy_v2():
    """Rename retired v2 blueprints out of the way (never delete)."""
    ensure_folder(LEGACY_BACKUP_ROOT)
    for path in LEGACY_V2_ASSETS:
        if not unreal.EditorAssetLibrary.does_asset_exist(path):
            continue
        name = path.rsplit("/", 1)[-1]
        dest = "%s/%s" % (LEGACY_BACKUP_ROOT, name)
        if unreal.EditorAssetLibrary.does_asset_exist(dest):
            unreal.EditorAssetLibrary.delete_asset(path)
        else:
            unreal.EditorAssetLibrary.rename_asset(path, dest)
        report["archived_legacy"].append(path)


def main():
    archive_legacy_v2()
    for name, folder, native_class in TARGETS:
        try:
            create_blueprint(folder, name, native_class)
        except Exception as exc:  # keep going, report at the end
            report["fail"] = True
            unreal.log_error("[GravityShift] install failed for %s: %s" % (name, exc))

    out_dir = os.path.join(unreal.Paths.project_saved_dir(), "GravityShift")
    os.makedirs(out_dir, exist_ok=True)
    out_file = os.path.join(out_dir, "INSTALL_BLUEPRINTS.json")
    with open(out_file, "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=1, ensure_ascii=False)

    unreal.log("[GravityShift] install_blueprints created=%d reused=%d preserved=%d fallback=%d archived=%d fail=%s"
               % (len(report["created"]), len(report["reused"]), len(report["preserved"]),
                  len(report["fallbacks"]), len(report["archived_legacy"]), report["fail"]))
    unreal.log("[GravityShift] report -> %s" % out_file)


main()
